Version 2.12.0

diff --git a/usr/bin/czertainly-status b/usr/bin/czertainly-status
--- a/usr/bin/czertainly-status
+++ b/usr/bin/czertainly-status
@@ -4,34 +4,38 @@ czertainly-versions
 echo ""
 
 declare -a NS=( 'kube-system' 'cert-manager' 'czertainly' )
-
-kubectl='/var/lib/rancher/rke2/bin/kubectl'
-
 scriptName=`basename $0`
+
+detailed=$([[ "$1" == "--detailed" ]] && echo 1 || echo 0)
 
 OK=0
 for ns in ${NS[@]};
 do
     tmpf=`mktemp /tmp/$scriptName-$ns-XXXX`
     tmpf_err="${tmpf}_err"
-    cmd="$kubectl get pods -n "$ns" --no-headers=true"
-    if output=$(sudo $cmd 2>$tmpf_err | grep -v 'ingress-nginx-controller.*Pending' >$tmpf)
+    cmd="kubectl get pods -n "$ns" --no-headers=true"
+    if output=$($cmd 2>$tmpf_err | grep -v 'ingress-nginx-controller.*Pending' >$tmpf)
     then
-	total_cnt=`cat $tmpf | wc -l`
-	running_cnt=`cat $tmpf | tr -s ' ' | cut -f 3 -d ' ' | grep Running | wc -l`
-	completed_cnt=`cat $tmpf | tr -s ' ' | cut -f 3 -d ' ' | grep Completed | wc -l`
-	done_cnt=$(($running_cnt + $completed_cnt))
-	if [ $total_cnt -gt 0 ] && [ $total_cnt -eq $done_cnt ]
-	then
-	    echo "$ns	$running_cnt PODs OK"
-	    OK=$(( $OK+1 ))
-	else
-	    echo "$ns	only $done_cnt of $total_cnt PODs are fine"
-	    cat $tmpf | sed "s/^/  /"
-	fi
+        total_cnt=`cat $tmpf | wc -l`
+        running_cnt=`cat $tmpf | tr -s ' ' | cut -f 3 -d ' ' | grep Running | wc -l`
+        completed_cnt=`cat $tmpf | tr -s ' ' | cut -f 3 -d ' ' | grep Completed | wc -l`
+        done_cnt=$(($running_cnt + $completed_cnt))
+        if [ $total_cnt -gt 0 ] && [ $total_cnt -eq $done_cnt ]
+        then
+            echo "$ns	$running_cnt PODs OK"
+            OK=$(( $OK+1 ))
+        else
+            echo "$ns	only $done_cnt of $total_cnt PODs are fine"
+            cat $tmpf | sed "s/^/  /"
+        fi
+        if [ $detailed -ne 0 ] && [ "$ns" == 'czertainly' ]
+        then
+            echo "czertainly versions:"
+            kubectl -n $ns get pods -o jsonpath='{range .items[*]}{"  "}{.metadata.labels.app\.kubernetes\.io/name}{":  "}{range .spec.containers[*]}{.image}{" "}{end}{"\n"}{end}'
+        fi
     else
-	output_err=`cat $tmpf_err`
-	echo "Failed to exec $cmd: $output_err"
+        output_err=`cat $tmpf_err`
+        echo "Failed to exec $cmd: $output_err"
     fi
     rm $tmpf
     rm $tmpf_err
diff --git a/usr/bin/czertainly-versions b/usr/bin/czertainly-versions
--- a/usr/bin/czertainly-versions
+++ b/usr/bin/czertainly-versions
@@ -15,3 +15,16 @@ then
 fi
 
 echo "appliance: $APPLIANCE_VERSION; tools: $TOOLS_VERSION; chart: $CHART_VERSION"
+
+if [ "$1" == '--detailed' ]
+then
+  if kubectl version >/dev/null 2>&1
+  then
+    echo ""
+    kubectl get pods -n czertainly -o jsonpath='{range .items[*]}{.metadata.labels.app\.kubernetes\.io/name}{"\n"}{range .spec.initContainers[*]}  init: {.image}{"\n"}{end}{range .spec.containers[*]}  cont: {.image}{"\n"}{end}{end}'
+  else
+    echo ""
+    echo "missing or mailfunction kubectl can't provide more informations"
+    exit 1
+  fi
+fi
